- name: Configure Web Servers
  hosts: all
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Deploy Website
      copy:
        content: "<h1>Welcome to the Load Balanced Web Server!</h1>"
        dest: /var/www/html/index.html
